language: node_js
node_js:
- lts/*
- '9'
- '8'
services:
- elasticsearch
- postgresql
- redis-server
addons:
  postgresql: 9.6
before_script:
- sleep 10
script:
- npm run lint
- npm run test-travis
before_deploy:
  - |
    if [ "$TRAVIS_TAG" != "" ];
    then
      npm version $TRAVIS_TAG
    fi
deploy:
- provider: npm
  tag: alpha
  api_key:
    secure: MRZ94BYLLycJe1sOS6VZtR8EFA8XNhduIgxpVnsryMdlvCZc6fk3bOWe506mifT4EWFicNt2H5wRKiFAIVGHVVTftAsg8XZXx52PwnNfKwS5YcgU36oDCgAVSMLvReHIPiyp9ElBq/evZFMjIkIZsLZgw5g2zPlOGi9d+mHwrJCH/DDnBBRlq1f+7kUBEO6hFOLFIw5LAQ0hSIgdh0ikd+5Am2G3P3U8Gni8vFISaHqzuy1xqCRrpvPXIomruRGFN6B+Fau04XqROPGNa+6d/QJWVpEaAcyWmdY8xssnJuSyyPSEsESbzwmvdaZAGXi7nzVdY6LjTFS8li5rVyFasXXZJBBKdvXqY3e01pwoEx7+33NdhCAlNL+sYXuWcXAxZbnHeaG0EWuPW5PRj7jtwtCQkT3E0VgiBvSPHqqzyYwLF9LaxCaqAJMa9BbUEV8Mt9j0p5H5SW6XUWT5LNJ2DTMtN7GxK4FFDKjrmewoXDuwYFPFhnKgPVFNXp4ZqHMy7icVP28SBgGs6fEzsjNRns/nX0SmET//LjOQmy1/utKZWxZy+d3Vc/da6Gy/mzm1rnKbIs81UfkEGFHgxZlHyOqNeNFfU17WajXsG1XKjgDJPdgxsK6udn2r1rOHzKWE8MVNU43oN1l+7aZvD2njBId5bRPTBGuosBiqzsuPNHk=
  email:
    secure: bkrHIfTtuWzoFdOoiYjYUztwKU5ZiuZICKVdDH+Bb4HyqPcmDFN6nQTfVYpTw/zwXu/WN/O8MSqNJpHIuzRIi+8F94QHBmPbNy7MxSL62eYum3iq8AVdemPUvb5cbjsiCT4J95VgpIkvFd8p1l348C16STDY6zRTWW884ZvPpe+JptkfDIxHePaJqqV2FNz5Rw9JoCZukk0ieulpylS9gu4HxFvztb29WCX7i12ZGQZ8bvJk8exXn1tNHsqmpxvmtP9HYHLGNLqBT8IGfcNqtBVss6ldZ7wwf5FDe9sXaXTDfHBD9uLno1gnv4gm+gXsLHBWcxDm6yjF7pkUPGh9rvvOB/wS3v2l2c8KUQJhioDr//YgTEHat7jt4M5dnoC7UrpqmODM56xN2q+HwF1AHxTSg3oomrp/F8NOO/7qDCj8BBQb5qq9IZaEy/4DDKRMj3kqjFzPW3xkIFnl34r5Ho1FDdfHVYufEld2xAXAis/vzX8g6fxIcgAzQric2HFhgC/z9g9qBCvTZhNgsPyUmfI8B72dbrrAeYmC0+QOu1zqXRXksHOf9DBzjex7XnYy3k6I7WzfPIhV14PqIZNfp2QjeV4DmjKidti7el3qRNM/cQqPoU4gjj3MjfQgUukd4nuJFo1i3Kg6v3dSA6BIZUdo5ujwjIA2+1CV/RmxTbs=
  on:
    condition: "$TRAVIS_TAG =~ alpha"
    all_branches: true
    tags: true
- provider: npm
  tag: beta
  api_key:
    secure: MRZ94BYLLycJe1sOS6VZtR8EFA8XNhduIgxpVnsryMdlvCZc6fk3bOWe506mifT4EWFicNt2H5wRKiFAIVGHVVTftAsg8XZXx52PwnNfKwS5YcgU36oDCgAVSMLvReHIPiyp9ElBq/evZFMjIkIZsLZgw5g2zPlOGi9d+mHwrJCH/DDnBBRlq1f+7kUBEO6hFOLFIw5LAQ0hSIgdh0ikd+5Am2G3P3U8Gni8vFISaHqzuy1xqCRrpvPXIomruRGFN6B+Fau04XqROPGNa+6d/QJWVpEaAcyWmdY8xssnJuSyyPSEsESbzwmvdaZAGXi7nzVdY6LjTFS8li5rVyFasXXZJBBKdvXqY3e01pwoEx7+33NdhCAlNL+sYXuWcXAxZbnHeaG0EWuPW5PRj7jtwtCQkT3E0VgiBvSPHqqzyYwLF9LaxCaqAJMa9BbUEV8Mt9j0p5H5SW6XUWT5LNJ2DTMtN7GxK4FFDKjrmewoXDuwYFPFhnKgPVFNXp4ZqHMy7icVP28SBgGs6fEzsjNRns/nX0SmET//LjOQmy1/utKZWxZy+d3Vc/da6Gy/mzm1rnKbIs81UfkEGFHgxZlHyOqNeNFfU17WajXsG1XKjgDJPdgxsK6udn2r1rOHzKWE8MVNU43oN1l+7aZvD2njBId5bRPTBGuosBiqzsuPNHk=
  email:
    secure: bkrHIfTtuWzoFdOoiYjYUztwKU5ZiuZICKVdDH+Bb4HyqPcmDFN6nQTfVYpTw/zwXu/WN/O8MSqNJpHIuzRIi+8F94QHBmPbNy7MxSL62eYum3iq8AVdemPUvb5cbjsiCT4J95VgpIkvFd8p1l348C16STDY6zRTWW884ZvPpe+JptkfDIxHePaJqqV2FNz5Rw9JoCZukk0ieulpylS9gu4HxFvztb29WCX7i12ZGQZ8bvJk8exXn1tNHsqmpxvmtP9HYHLGNLqBT8IGfcNqtBVss6ldZ7wwf5FDe9sXaXTDfHBD9uLno1gnv4gm+gXsLHBWcxDm6yjF7pkUPGh9rvvOB/wS3v2l2c8KUQJhioDr//YgTEHat7jt4M5dnoC7UrpqmODM56xN2q+HwF1AHxTSg3oomrp/F8NOO/7qDCj8BBQb5qq9IZaEy/4DDKRMj3kqjFzPW3xkIFnl34r5Ho1FDdfHVYufEld2xAXAis/vzX8g6fxIcgAzQric2HFhgC/z9g9qBCvTZhNgsPyUmfI8B72dbrrAeYmC0+QOu1zqXRXksHOf9DBzjex7XnYy3k6I7WzfPIhV14PqIZNfp2QjeV4DmjKidti7el3qRNM/cQqPoU4gjj3MjfQgUukd4nuJFo1i3Kg6v3dSA6BIZUdo5ujwjIA2+1CV/RmxTbs=
  on:
    condition: "$TRAVIS_TAG =~ beta"
    all_branches: true
    tags: true
- provider: npm
  tag: rc
  api_key:
    secure: MRZ94BYLLycJe1sOS6VZtR8EFA8XNhduIgxpVnsryMdlvCZc6fk3bOWe506mifT4EWFicNt2H5wRKiFAIVGHVVTftAsg8XZXx52PwnNfKwS5YcgU36oDCgAVSMLvReHIPiyp9ElBq/evZFMjIkIZsLZgw5g2zPlOGi9d+mHwrJCH/DDnBBRlq1f+7kUBEO6hFOLFIw5LAQ0hSIgdh0ikd+5Am2G3P3U8Gni8vFISaHqzuy1xqCRrpvPXIomruRGFN6B+Fau04XqROPGNa+6d/QJWVpEaAcyWmdY8xssnJuSyyPSEsESbzwmvdaZAGXi7nzVdY6LjTFS8li5rVyFasXXZJBBKdvXqY3e01pwoEx7+33NdhCAlNL+sYXuWcXAxZbnHeaG0EWuPW5PRj7jtwtCQkT3E0VgiBvSPHqqzyYwLF9LaxCaqAJMa9BbUEV8Mt9j0p5H5SW6XUWT5LNJ2DTMtN7GxK4FFDKjrmewoXDuwYFPFhnKgPVFNXp4ZqHMy7icVP28SBgGs6fEzsjNRns/nX0SmET//LjOQmy1/utKZWxZy+d3Vc/da6Gy/mzm1rnKbIs81UfkEGFHgxZlHyOqNeNFfU17WajXsG1XKjgDJPdgxsK6udn2r1rOHzKWE8MVNU43oN1l+7aZvD2njBId5bRPTBGuosBiqzsuPNHk=
  email:
    secure: bkrHIfTtuWzoFdOoiYjYUztwKU5ZiuZICKVdDH+Bb4HyqPcmDFN6nQTfVYpTw/zwXu/WN/O8MSqNJpHIuzRIi+8F94QHBmPbNy7MxSL62eYum3iq8AVdemPUvb5cbjsiCT4J95VgpIkvFd8p1l348C16STDY6zRTWW884ZvPpe+JptkfDIxHePaJqqV2FNz5Rw9JoCZukk0ieulpylS9gu4HxFvztb29WCX7i12ZGQZ8bvJk8exXn1tNHsqmpxvmtP9HYHLGNLqBT8IGfcNqtBVss6ldZ7wwf5FDe9sXaXTDfHBD9uLno1gnv4gm+gXsLHBWcxDm6yjF7pkUPGh9rvvOB/wS3v2l2c8KUQJhioDr//YgTEHat7jt4M5dnoC7UrpqmODM56xN2q+HwF1AHxTSg3oomrp/F8NOO/7qDCj8BBQb5qq9IZaEy/4DDKRMj3kqjFzPW3xkIFnl34r5Ho1FDdfHVYufEld2xAXAis/vzX8g6fxIcgAzQric2HFhgC/z9g9qBCvTZhNgsPyUmfI8B72dbrrAeYmC0+QOu1zqXRXksHOf9DBzjex7XnYy3k6I7WzfPIhV14PqIZNfp2QjeV4DmjKidti7el3qRNM/cQqPoU4gjj3MjfQgUukd4nuJFo1i3Kg6v3dSA6BIZUdo5ujwjIA2+1CV/RmxTbs=
  on:
    condition: "$TRAVIS_TAG =~ rc"
    all_branches: true
    tags: true
- provider: npm
  api_key:
    secure: MRZ94BYLLycJe1sOS6VZtR8EFA8XNhduIgxpVnsryMdlvCZc6fk3bOWe506mifT4EWFicNt2H5wRKiFAIVGHVVTftAsg8XZXx52PwnNfKwS5YcgU36oDCgAVSMLvReHIPiyp9ElBq/evZFMjIkIZsLZgw5g2zPlOGi9d+mHwrJCH/DDnBBRlq1f+7kUBEO6hFOLFIw5LAQ0hSIgdh0ikd+5Am2G3P3U8Gni8vFISaHqzuy1xqCRrpvPXIomruRGFN6B+Fau04XqROPGNa+6d/QJWVpEaAcyWmdY8xssnJuSyyPSEsESbzwmvdaZAGXi7nzVdY6LjTFS8li5rVyFasXXZJBBKdvXqY3e01pwoEx7+33NdhCAlNL+sYXuWcXAxZbnHeaG0EWuPW5PRj7jtwtCQkT3E0VgiBvSPHqqzyYwLF9LaxCaqAJMa9BbUEV8Mt9j0p5H5SW6XUWT5LNJ2DTMtN7GxK4FFDKjrmewoXDuwYFPFhnKgPVFNXp4ZqHMy7icVP28SBgGs6fEzsjNRns/nX0SmET//LjOQmy1/utKZWxZy+d3Vc/da6Gy/mzm1rnKbIs81UfkEGFHgxZlHyOqNeNFfU17WajXsG1XKjgDJPdgxsK6udn2r1rOHzKWE8MVNU43oN1l+7aZvD2njBId5bRPTBGuosBiqzsuPNHk=
  email:
    secure: bkrHIfTtuWzoFdOoiYjYUztwKU5ZiuZICKVdDH+Bb4HyqPcmDFN6nQTfVYpTw/zwXu/WN/O8MSqNJpHIuzRIi+8F94QHBmPbNy7MxSL62eYum3iq8AVdemPUvb5cbjsiCT4J95VgpIkvFd8p1l348C16STDY6zRTWW884ZvPpe+JptkfDIxHePaJqqV2FNz5Rw9JoCZukk0ieulpylS9gu4HxFvztb29WCX7i12ZGQZ8bvJk8exXn1tNHsqmpxvmtP9HYHLGNLqBT8IGfcNqtBVss6ldZ7wwf5FDe9sXaXTDfHBD9uLno1gnv4gm+gXsLHBWcxDm6yjF7pkUPGh9rvvOB/wS3v2l2c8KUQJhioDr//YgTEHat7jt4M5dnoC7UrpqmODM56xN2q+HwF1AHxTSg3oomrp/F8NOO/7qDCj8BBQb5qq9IZaEy/4DDKRMj3kqjFzPW3xkIFnl34r5Ho1FDdfHVYufEld2xAXAis/vzX8g6fxIcgAzQric2HFhgC/z9g9qBCvTZhNgsPyUmfI8B72dbrrAeYmC0+QOu1zqXRXksHOf9DBzjex7XnYy3k6I7WzfPIhV14PqIZNfp2QjeV4DmjKidti7el3qRNM/cQqPoU4gjj3MjfQgUukd4nuJFo1i3Kg6v3dSA6BIZUdo5ujwjIA2+1CV/RmxTbs=
  on:
    condition: "$TRAVIS_TAG =~ ^((?!alpha|beta|rc).)"
    all_branches: true
    tags: true

