language: node_js
node_js:
  - "lts/*"
  - "9"
  - "8"
services:
  - elasticsearch
  - postgresql
  - redis-server
addons:
  postgresql: 9.6
before_script:
  - sleep 10
script:
  - npm run lint
  - npm run test-travis